baseurl:
markdown: kramdown
permalink: /:categories/:title/

ga_tracking_code:
p2pu_ga_tracking_code:

exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules"
    values:
      layout: "course_page"

prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

jumbotron_color: "#000000"
jumbotron_background_image: "header.svg"
jumbotron_image: "box-icon.png"